# coding=utf-8
columns_cn=[
"id",
"性别",
"年龄",
"体检日期",
"*天门冬氨酸氨基转换酶",
"*丙氨酸氨基转换酶",
"*碱性磷酸酶",
"*r-谷氨酰基转换酶",
"*总蛋白",
"白蛋白",
"*球蛋白",
"白球比例",
"甘油三酯",
"总胆固醇",
"高密度脂蛋白胆固醇",
"低密度脂蛋白胆固醇",
"尿素",
"肌酐",
"尿酸",
"乙肝表面抗原",
"乙肝表面抗体",
"乙肝e抗原",
"乙肝e抗体",
"乙肝核心抗体",
"白细胞计数",
"红细胞计数",
"血红蛋白",
"红细胞压积",
"红细胞平均体积",
"红细胞平均血红蛋白量",
"红细胞平均血红蛋白浓度",
"红细胞体积分布宽度",
"血小板计数",
"血小板平均体积",
"血小板体积分布宽度",
"血小板比积",
"中性粒细胞%",
"淋巴细胞%",
"单核细胞%",
"嗜酸细胞%",
"嗜碱细胞%",
"血糖"]


columns_en=[
"id",
"gender",
"age",
"Physical examination date",
"* Aspartate aminotransferase",
"* Alanine aminotransferase",
"* Alkaline phosphatase",
"* r-glutamyl converting enzyme",
"*Total protein",
"albumin",
"*globulin",
"White ball ratio",
"Triglycerides",
"Total cholesterol",
"High density lipoprotein cholesterol",
"Low-density lipoprotein cholesterol",
"Urea",
"Creatinine",
"Uric acid",
"Hepatitis B surface antigen",
"Hepatitis B surface antibody",
"Hepatitis B e antigen",
"Hepatitis B e antibody",
"Hepatitis B core antibody",
"White blood cell count",
"Red blood cell count",
"Hemoglobin",
"Hematocrit",
"Average volume of red blood cells",
"Red blood cell average hemoglobin amount",
"Erythrocyte average hemoglobin concentration",
"Red blood cell volume distribution width",
"Platelet count",
"Average platelet volume",
"Platelet Volume Distribution Width",
"Platelet product than",
"Neutrophil%",
"Lymphocyte%",
"% Monocytes",
"Eosinophil%",
"Basophil%",
"blood sugar"
]
# print columns_en
choose=['gender',
'age',
'White blood cell count',
'Red blood cell count',
'Hemoglobin',
'Hematocrit',
'Average volume of red blood cells',
'Red blood cell average hemoglobin amount',
'Erythrocyte average hemoglobin concentration',
'Red blood cell volume distribution width',
'Platelet count',
'Average platelet volume',
'Platelet Volume Distribution Width',
'Platelet product than',
'Neutrophil%',
'Lymphocyte%',
'% Monocytes',
'Eosinophil%',
'Basophil%']

classify_columns=[
    'gender', 'age', '* Alkaline phosphatase', 'Triglycerides',
    'Total cholesterol', 'Low-density lipoprotein cholesterol', 'Urea',
    'Creatinine', 'Uric acid', 'Hepatitis B surface antibody',
    'White blood cell count', 'Red blood cell count', 'Hemoglobin',
    'Hematocrit'
]